-- supabase/seed.sql
-- Wird automatisch von 'supabase db reset' nach den Migrationen ausgefuehrt.
-- Enthaelt 2084 deutsche Tiere.

with new_animals(name) as (values
  ('Aal'),
  ('Aalessinier'),
  ('Aalmutter'),
  ('Aalraupe'),
  ('Aasgeier'),
  ('Aaskäfer'),
  ('Abalone'),
  ('Abendpfauenauge'),
  ('Abendsegler'),
  ('Abgottschlange'),
  ('Addax'),
  ('Adelie-Pinguin'),
  ('Adler'),
  ('Adlerbussard'),
  ('Adlerrochen'),
  ('Affe'),
  ('Affenadler'),
  ('Affenpinscher'),
  ('Afrikanische Goldkatze'),
  ('Afrikanische Wildkatze'),
  ('Afrikanischer Büffel'),
  ('Afrikanischer Elefant'),
  ('Afrikanischer Strauß'),
  ('Afrikanischer Wildhund'),
  ('Aga-Kröte'),
  ('Agame'),
  ('Aguti'),
  ('Airedale Terrier'),
  ('Akbash'),
  ('Akita'),
  ('Alaska-Seelachs'),
  ('Alaskan Malamute'),
  ('Albatros'),
  ('Albino-Python'),
  ('Allgäuer Braunvieh'),
  ('Alligator'),
  ('Alligatorhecht'),
  ('Alpaca'),
  ('Alpaka'),
  ('Alpenbock'),
  ('Alpenbraunelle'),
  ('Alpendohle'),
  ('Alpenkrähe'),
  ('Alpenmurmeltier'),
  ('Alpensalamander'),
  ('Alpenschneehuhn'),
  ('Alpensegler'),
  ('Alpenstrandläufer'),
  ('Altweltaffe'),
  ('Amazonas-Delfin'),
  ('Amazonenpapagei'),
  ('Ameise'),
  ('Ameisenbär'),
  ('Ameisenigel'),
  ('Ameisenlöwe'),
  ('Ameisenwolf'),
  ('American Akita'),
  ('American Bulldog'),
  ('American Cocker Spaniel'),
  ('American Eskimo Dog'),
  ('American Foxhound'),
  ('American Pit Bull Terrier'),
  ('American Staffordshire Terrier'),
  ('Amerikanischer Bison'),
  ('Amerikanischer Schwarzbär'),
  ('Amphibie'),
  ('Amsel'),
  ('Amsterdam-Albatros'),
  ('Amurleopard'),
  ('Amurtiger'),
  ('Anakonda'),
  ('Anatolische Katze'),
  ('Anatolischer Hirtenhund'),
  ('Anchovis'),
  ('Andenflamingo'),
  ('Andenkondor'),
  ('Andenwildkatze'),
  ('Angelfisch'),
  ('Anglerfisch'),
  ('Anolis'),
  ('Antarktischer Krill'),
  ('Antilope'),
  ('Apollofalter'),
  ('Appenzeller Sennenhund'),
  ('Aquilops'),
  ('Ara'),
  ('Arabische Mau'),
  ('Arabischer Leopard'),
  ('Arapaho-Wolf'),
  ('Arapaima'),
  ('Archaeopteryx'),
  ('Argusfasan'),
  ('Arielreiher'),
  ('Arktischer Fuchs'),
  ('Arktischer Polarfuchs'),
  ('Armadillo'),
  ('Asiatischer Elefant'),
  ('Asiatischer Löwe'),
  ('Asiatischer Schwarzbär'),
  ('Asiatischer Wildhund'),
  ('Assel'),
  ('Atlantische Lachsforelle'),
  ('Atlantischer Lachs'),
  ('Atlantischer Stör'),
  ('Atlas-Hirschkäfer'),
  ('Atlasspinner'),
  ('Auerhuhn'),
  ('Aurorafalter'),
  ('Austernfischer'),
  ('Australian Cattle Dog'),
  ('Australian Kelpie'),
  ('Australian Shepherd'),
  ('Australian Silky Terrier'),
  ('Australian Terrier'),
  ('Australischer Beutelteufel'),
  ('Avocet'),
  ('Axolotl'),
  ('Babirusa'),
  ('Bachforelle'),
  ('Bachneunauge'),
  ('Bachsaibling'),
  ('Bachschmerle'),
  ('Bachstelze'),
  ('Baikalrobbe'),
  ('Balinese'),
  ('Bananenfalter'),
  ('Bandschwanzbussard'),
  ('Bandwurm'),
  ('Bantamhuhn'),
  ('Barbet'),
  ('Barsch'),
  ('Bartagame'),
  ('Bartgeier'),
  ('Bartkauz'),
  ('Bartmeise'),
  ('Bartrobbe'),
  ('Basenji'),
  ('Basilisk'),
  ('Basset Hound'),
  ('Basstölpel'),
  ('Baumeidechse'),
  ('Baumhörnchen'),
  ('Baumkänguru'),
  ('Baumläufer'),
  ('Baummarder'),
  ('Baumpython'),
  ('Baumralle'),
  ('Baumsteigerfrosch'),
  ('Beagle'),
  ('Bearded Collie'),
  ('Beauceron'),
  ('Beaver'),
  ('Bedlington Terrier'),
  ('Beifußhuhn'),
  ('Belgischer Schäferhund'),
  ('Beluga'),
  ('Belugastör'),
  ('Bengal'),
  ('Beo'),
  ('Bergdohle'),
  ('Berger Blanc Suisse'),
  ('Berger de Picardie'),
  ('Bergfink'),
  ('Berggorilla'),
  ('Bergkänguru'),
  ('Bergmolch'),
  ('Bergpapagei'),
  ('Bergpieper'),
  ('Bergtapir'),
  ('Bergzebra'),
  ('Bermudasturmvogel'),
  ('Berner Sennenhund'),
  ('Bernhardiner'),
  ('Bernstein-Waldschabe'),
  ('Bettwanze'),
  ('Beutelmarder'),
  ('Beutelmaus'),
  ('Beutelratte'),
  ('Beutelteufel'),
  ('Beutelwolf'),
  ('Biber'),
  ('Bichon Frisé'),
  ('Biene'),
  ('Bienenfresser'),
  ('Bienenwolf'),
  ('Biewer Terrier'),
  ('Bilch'),
  ('Binturong'),
  ('Birkenmaus'),
  ('Birkenzeisig'),
  ('Birkhuhn'),
  ('Birma'),
  ('Bisam'),
  ('Bison'),
  ('Bitterling'),
  ('Blattkäfer'),
  ('Blattschneiderameise'),
  ('Blattschwanzgecko'),
  ('Blaubussard'),
  ('Blauflügelente'),
  ('Blaufußtölpel'),
  ('Blauhai'),
  ('Blaukappentangare'),
  ('Blaukehlchen'),
  ('Blaukrabbe'),
  ('Blaumeise'),
  ('Blauracke'),
  ('Blauwal'),
  ('Blauzungenskink'),
  ('Blindfisch'),
  ('Blindschleiche'),
  ('Bloodhound'),
  ('Blutbiene'),
  ('Blutegel'),
  ('Blutsauger'),
  ('Blässhuhn'),
  ('Boa'),
  ('Bobail'),
  ('Bockkäfer'),
  ('Bombay-Katze'),
  ('Bonefish'),
  ('Bongo'),
  ('Bonobo'),
  ('Boomslang'),
  ('Border Collie'),
  ('Border Terrier'),
  ('Borzoi'),
  ('Boston Terrier'),
  ('Bouvier des Flandres'),
  ('Boxer'),
  ('Bracco Italiano'),
  ('Brachvogel'),
  ('Brandente'),
  ('Brandgans'),
  ('Brandseeschwalbe'),
  ('Branta'),
  ('Brassen'),
  ('Braunbär'),
  ('Brauner Eremit'),
  ('Braunkehlchen'),
  ('Braunkopf-Kuhstärling'),
  ('Breitmaulnashorn'),
  ('Briard'),
  ('Brillenbär'),
  ('Brillenkaiman'),
  ('Brillenkauz'),
  ('Brillenpelikan'),
  ('Brillenpinguin'),
  ('Brillensalamander'),
  ('Brillenschlange'),
  ('Britische Kurzhaarkatze'),
  ('Britische Langhaarkatze'),
  ('Broholmer'),
  ('Brüllaffe'),
  ('Buchfasan'),
  ('Buchfink'),
  ('Buckelwal'),
  ('Bull Terrier'),
  ('Bulldogge'),
  ('Bullmastiff'),
  ('Buntbarsch'),
  ('Buntfalke'),
  ('Buntsittich'),
  ('Buntspecht'),
  ('Burenziege'),
  ('Burmese'),
  ('Burmilla'),
  ('Buschbock'),
  ('Buschelefant'),
  ('Buschhuhn'),
  ('Buschhund'),
  ('Buschkrokodil'),
  ('Buschmeister'),
  ('Buschspringer'),
  ('Bär'),
  ('Büffel'),
  ('Caiman'),
  ('Cairn Terrier'),
  ('Cane Corso'),
  ('Caracara'),
  ('Cassowary'),
  ('Catalanischer Schäferhund'),
  ('Cavalier King Charles Spaniel'),
  ('Cayenne-Schildkröte'),
  ('Cebu-Höhlenfrosch'),
  ('Cesky Terrier'),
  ('Ceylon-Hutaffe'),
  ('Chamaeleo'),
  ('Chamäleon'),
  ('Chartreux'),
  ('Chausie'),
  ('Chesapeake Bay Retriever'),
  ('Chichimeko'),
  ('Chihuahua'),
  ('Chileflamingo'),
  ('Chinastör'),
  ('Chinchilla'),
  ('Chinesische Gottesanbeterin'),
  ('Chinesischer Alligator'),
  ('Chinesischer Mauergecko'),
  ('Chinesischer Riesensalamander'),
  ('Chinesischer Schopfhund'),
  ('Chinesischer Wasserhirsch'),
  ('Chinook Lachs'),
  ('Chow-Chow'),
  ('Clownfisch'),
  ('Clumber Spaniel'),
  ('Cocker Spaniel'),
  ('Coelacanth'),
  ('Collie'),
  ('Condor'),
  ('Corgi'),
  ('Cornish Rex'),
  ('Coton de Tuléar'),
  ('Coyote'),
  ('Curly Coated Retriever'),
  ('Dachs'),
  ('Dachsbär'),
  ('Dackel'),
  ('Dahomey-Rind'),
  ('Dalmatiner'),
  ('Damhirsch'),
  ('Damwild'),
  ('Darwinfink'),
  ('Daubentonia'),
  ('Daunenente'),
  ('Davidshirsch'),
  ('Deerhound'),
  ('Degu'),
  ('Delfin'),
  ('Deutsch Drahthaar'),
  ('Deutsch Kurzhaar'),
  ('Deutsche Dogge'),
  ('Deutscher Boxer'),
  ('Deutscher Jagdterrier'),
  ('Deutscher Pinscher'),
  ('Deutscher Schäferhund'),
  ('Devon Rex'),
  ('Diademmeerkatze'),
  ('Diamantfasan'),
  ('Diamantklapperschlange'),
  ('Diamantkleinfisch'),
  ('Diamantpython'),
  ('Dibatag'),
  ('Dickhornschaf'),
  ('Dickkopffalter'),
  ('Dikdik'),
  ('Dingo'),
  ('Dinosaurier'),
  ('Diskusfisch'),
  ('Dobermann'),
  ('Dogo Argentino'),
  ('Dogue de Bordeaux'),
  ('Dohle'),
  ('Dohlenkrähe'),
  ('Dolch-Wespe'),
  ('Dompfaff'),
  ('Donkoy'),
  ('Doppelhornvogel'),
  ('Doppelschleiche'),
  ('Dorade'),
  ('Dornenkronenseestern'),
  ('Dornhai'),
  ('Dornschwanz'),
  ('Dorsch'),
  ('Drachenfisch'),
  ('Drachenkopf'),
  ('Dreifingerfaultier'),
  ('Dreizehenmöwe'),
  ('Dromedar'),
  ('Drossel'),
  ('Druckerameise'),
  ('Dschungelkatze'),
  ('Dugong'),
  ('Dunkler Tigerpython'),
  ('Dunkler Wassermolch'),
  ('Düstervogel'),
  ('Echse'),
  ('Echsenkopf'),
  ('Edelfalter'),
  ('Edelfasan'),
  ('Edelkrebs'),
  ('Edelpapagei'),
  ('Edelstein-Smaragdeidechse'),
  ('Eichelhäher'),
  ('Eichhörnchen'),
  ('Eidechse'),
  ('Eiderente'),
  ('Einhornfisch'),
  ('Einsiedlerkrebs'),
  ('Eintagsfliege'),
  ('Eisbär'),
  ('Eisente'),
  ('Eisfuchs'),
  ('Eisvogel'),
  ('Elch'),
  ('Elefant'),
  ('Elefantenrobbe'),
  ('Elenantilope'),
  ('Elo'),
  ('Elritze'),
  ('Elritzenwels'),
  ('Elster'),
  ('Elsterdrossel'),
  ('Emu'),
  ('Engelhai'),
  ('Ente'),
  ('Entlebucher Sennenhund'),
  ('Erdaal'),
  ('Erdferkel'),
  ('Erdhummel'),
  ('Erdkröte'),
  ('Erdmaus'),
  ('Erdmännchen'),
  ('Erdwaran'),
  ('Erdwolf'),
  ('Erdziesel'),
  ('Erleneule'),
  ('Esel'),
  ('Eulenfalter'),
  ('Eulenpapagei'),
  ('Eurasier'),
  ('Europäische Hornisse'),
  ('Europäische Kurzhaarkatze'),
  ('Europäische Sumpfschildkröte'),
  ('Europäischer Aal'),
  ('Europäischer Biber'),
  ('Europäischer Dachs'),
  ('Europäischer Feldhase'),
  ('Europäischer Hummer'),
  ('Europäischer Laubfrosch'),
  ('Europäischer Maulwurf'),
  ('Europäischer Nerz'),
  ('Europäischer Sumpfdrache'),
  ('Europäischer Wels'),
  ('Exotic Shorthair'),
  ('Fadenmolch'),
  ('Falbkatze'),
  ('Falke'),
  ('Fanaloka'),
  ('Fangschreckenkrebs'),
  ('Fasan'),
  ('Fasanenente'),
  ('Faultier'),
  ('Federflügelmotte'),
  ('Feldgrille'),
  ('Feldhamster'),
  ('Feldhase'),
  ('Feldlerche'),
  ('Feldmaus'),
  ('Felsenkänguru'),
  ('Felsenpinguin'),
  ('Felsentaube'),
  ('Fennek'),
  ('Fettschwanzmaus'),
  ('Feuerameise'),
  ('Feuerfisch'),
  ('Feuerfrosch'),
  ('Feuerkäfer'),
  ('Feuerqualle'),
  ('Feuersalamander'),
  ('Feuersalmler'),
  ('Feuerwanze'),
  ('Fichtenkreuzschnabel'),
  ('Field Spaniel'),
  ('Fila Brasileiro'),
  ('Fingertier'),
  ('Fink'),
  ('Finnischer Lapphund'),
  ('Finnwal'),
  ('Fischadler'),
  ('Fischotter'),
  ('Fischreiher'),
  ('Fischuhu'),
  ('Fjällräv'),
  ('Flachlandgorilla'),
  ('Flachlandtapir'),
  ('Flamingo'),
  ('Flamingo-Zunge'),
  ('Flat Coated Retriever'),
  ('Fleckenhyäne'),
  ('Fledermaus'),
  ('Fledermausspinne'),
  ('Fleischfliege'),
  ('Fliege'),
  ('Fliegender Fisch'),
  ('Floh'),
  ('Florettseidenschwanz'),
  ('Florfliege'),
  ('Flunder'),
  ('Flussadler'),
  ('Flussbarbe'),
  ('Flussbarsch'),
  ('Flussdelfin'),
  ('Flusshecht'),
  ('Flussjungfer'),
  ('Flusskrabbe'),
  ('Flusskrebs'),
  ('Flusspferd'),
  ('Flussregenpfeifer'),
  ('Flussschildkröte'),
  ('Flussuferläufer'),
  ('Folivora'),
  ('Forelle'),
  ('Forktail'),
  ('Fossa'),
  ('Fossae'),
  ('Foxterrier'),
  ('Französische Bulldogge'),
  ('Frauennerfling'),
  ('Frettchen'),
  ('Friesenpferd'),
  ('Fritzkröte'),
  ('Frosch'),
  ('Fruchtfliege'),
  ('Fruchttaube'),
  ('Frühlingsazurjungfer'),
  ('Fuchs'),
  ('Fuchshai'),
  ('Furchenwal'),
  ('Fuß-Mücke'),
  ('Fächerfisch'),
  ('Gabelbock'),
  ('Galagos'),
  ('Galanthus-Schildkröte'),
  ('Galapagos-Pinguin'),
  ('Galapagos-Schildkröte'),
  ('Galgo Español'),
  ('Gallaghers Schopfratte'),
  ('Gangesdelfin'),
  ('Gangesgavial'),
  ('Gans'),
  ('Garibaldifisch'),
  ('Garnelen'),
  ('Gartenbaumläufer'),
  ('Gartengrasmücke'),
  ('Gartenrotschwanz'),
  ('Gartenschläfer'),
  ('Gartenschnirkelschnecke'),
  ('Gauchara'),
  ('Gazelle'),
  ('Gebirgsstelze'),
  ('Geburtshelferkröte'),
  ('Gecko'),
  ('Gelbbauchunke'),
  ('Gelbbrustara'),
  ('Gelbbrustkrabbe'),
  ('Gelbe Mungorufratte'),
  ('Gelber Skorpion'),
  ('Gelbflossenthunfisch'),
  ('Gelbfußmöwe'),
  ('Gelbhalsmaus'),
  ('Gelbkehltrogon'),
  ('Gelbkopfgeier'),
  ('Gelbrandkäfer'),
  ('Gelbschnabelmilan'),
  ('Gemeine Wespe'),
  ('Gemeiner Sandregenwurm'),
  ('Gemse'),
  ('Gepard'),
  ('Gepunkteter Schlangenkopffisch'),
  ('Gerenuk'),
  ('Geschmückter Springer'),
  ('Getigerter Krötenfrosch'),
  ('Ghuderian'),
  ('Gibbon'),
  ('Gimpel'),
  ('Giraffe'),
  ('Glanzfasan'),
  ('Glanzkäfer'),
  ('Glasaal'),
  ('Glasfrosch'),
  ('Glaswels'),
  ('Glattotter'),
  ('Glattwal'),
  ('Gleitbeutler'),
  ('Gleitflieger'),
  ('Gleithörnchen'),
  ('Glupschauge'),
  ('Glühwürmchen'),
  ('Goldammer'),
  ('Goldbarsch'),
  ('Goldbaumsteiger'),
  ('Golden Retriever'),
  ('Goldener Löwenäffchen'),
  ('Goldfasan'),
  ('Goldfisch'),
  ('Goldgrundel'),
  ('Goldhamster'),
  ('Goldhähnchen'),
  ('Goldkopflöwenäffchen'),
  ('Goldlöwenäffchen'),
  ('Goldmull'),
  ('Goldregenpfeifer'),
  ('Goldschakal'),
  ('Goldstaub-Taggecko'),
  ('Goral'),
  ('Gordon Setter'),
  ('Gorilla'),
  ('Gottesanbeterin'),
  ('Granatbarsch'),
  ('Grasaffe'),
  ('Grasfrosch'),
  ('Grashund'),
  ('Grashüpfer'),
  ('Grauer Wal'),
  ('Graugans'),
  ('Grauhörnchen'),
  ('Graukranich'),
  ('Graureiher'),
  ('Grauwolf'),
  ('Grauwürger'),
  ('Greifvogel'),
  ('Grevyzebra'),
  ('Greyhound'),
  ('Grille'),
  ('Grindwal'),
  ('Grizzlybär'),
  ('Groenendael'),
  ('Grottenolm'),
  ('Großer Münsterländer'),
  ('Großer Schweizer Sennenhund'),
  ('Grundel'),
  ('Grüne Mamba'),
  ('Grüne Meeresschildkröte'),
  ('Grüne Pythonschlange'),
  ('Grüner Leguan'),
  ('Grüner Pfau'),
  ('Grünfink'),
  ('Grünling'),
  ('Grünspecht'),
  ('Guanaco'),
  ('Gundi'),
  ('Guppy'),
  ('Gämse'),
  ('Gänsegeier'),
  ('Gürtelmull'),
  ('Gürteltier'),
  ('Habicht'),
  ('Haflinger'),
  ('Hagfish'),
  ('Hai'),
  ('Halbinselotter'),
  ('Halsbandpekari'),
  ('Halsbandschnäpper'),
  ('Halsbandsittich'),
  ('Halsbinden-Frankolin'),
  ('Hamadryasbaboon'),
  ('Hammerhai'),
  ('Hamster'),
  ('Hamster-Maus'),
  ('Hardun'),
  ('Harlekin-Garnele'),
  ('Harpyie'),
  ('Hartmann-Bergzebra'),
  ('Hase'),
  ('Haubenkormoran'),
  ('Haubenlerche'),
  ('Haubenmeise'),
  ('Haubentaucher'),
  ('Haubenwachtel'),
  ('Hausesel'),
  ('Hausfliege'),
  ('Hausgans'),
  ('Hauskatze'),
  ('Hausmaus'),
  ('Hauspferd'),
  ('Hausschwein'),
  ('Haussperling'),
  ('Haustaube'),
  ('Hausziege'),
  ('Havana Brown'),
  ('Havaneser'),
  ('Hecht'),
  ('Hechtaal'),
  ('Hechtbarsch'),
  ('Heckenbraunelle'),
  ('Heidekrautspanner'),
  ('Heidelibelle'),
  ('Heilbutt'),
  ('Heilige Birma'),
  ('Heilige Ibis'),
  ('Hektors-Delfin'),
  ('Helmkasuar'),
  ('Helmpinguin'),
  ('Helmspecht'),
  ('Hering'),
  ('Heringshai'),
  ('Heringsmöwe'),
  ('Hermelin'),
  ('Heuschreckenmaus'),
  ('Hexenfisch'),
  ('Hibernicus'),
  ('Highlander'),
  ('Himalaya-Schwarzbär'),
  ('Himalayakatze'),
  ('Hippocampus'),
  ('Hirsch'),
  ('Hirscheber'),
  ('Hirschkäfer'),
  ('Hochlandanole'),
  ('Hochlandgorilla'),
  ('Hochlandkuh'),
  ('Hokkaido'),
  ('Holzbiene'),
  ('Holzwespe'),
  ('Holzwurm'),
  ('Honigbiene'),
  ('Honigdachs'),
  ('Honigfresser'),
  ('Hornfrosch'),
  ('Hornisse'),
  ('Hornkoralle'),
  ('Hornotter'),
  ('Hornrabe'),
  ('Hornschnabelfink'),
  ('Hornviper'),
  ('Hottentottenente'),
  ('Hovawart'),
  ('Huchen'),
  ('Hufeisenkrebs'),
  ('Hufeisennase'),
  ('Hufeisennatter'),
  ('Huhn'),
  ('Humboldt-Pinguin'),
  ('Hummel'),
  ('Hund'),
  ('Hundertfüßer'),
  ('Hundskopfboa'),
  ('Hundswürger'),
  ('Husaraffe'),
  ('Husky'),
  ('Hutaffe'),
  ('Hyazinth-Ara'),
  ('Hyrax'),
  ('Hyäne'),
  ('Höckerschwan'),
  ('Höhlenfisch'),
  ('Höhlensalamander'),
  ('Hügelreiher'),
  ('Hüpferling'),
  ('Iberischer Luchs'),
  ('Iberischer Wolf'),
  ('Ibex'),
  ('Ibis'),
  ('Ichneumon'),
  ('Igel'),
  ('Iltis'),
  ('Impala'),
  ('Indianerwolf'),
  ('Indigoschlange'),
  ('Indischer Elefant'),
  ('Indisches Nashorn'),
  ('Indri'),
  ('Inkaseeschwalbe'),
  ('Iriomote-Katze'),
  ('Irischer Setter'),
  ('Irish Red Setter'),
  ('Irish Terrier'),
  ('Irish Wolfhound'),
  ('Isarerle'),
  ('Italienischer Apennin-Wolf'),
  ('Italienisches Windspiel'),
  ('Jack Russell Terrier'),
  ('Jagdfasan'),
  ('Jagdleopard'),
  ('Jagdspinne'),
  ('Jaguar'),
  ('Jaguarundi'),
  ('Jak'),
  ('Jangtse-Delfin'),
  ('Japan Chin'),
  ('Japanische Stummelschwanzkatze'),
  ('Japanischer Spitz'),
  ('Java-Nashorn'),
  ('Javanese'),
  ('Javaspatz'),
  ('Johnsonkrokodil'),
  ('Jonasfisch'),
  ('Junikäfer'),
  ('Kabeljau'),
  ('Kaffernbüffel'),
  ('Kaffernhuhn'),
  ('Kai'),
  ('Kaiman'),
  ('Kaiseradler'),
  ('Kaiserfisch'),
  ('Kaiserpinguin'),
  ('Kaiserschlange'),
  ('Kaiserschnurrbarttamarin'),
  ('Kakadu'),
  ('Kakapo'),
  ('Kalifornischer Kondor'),
  ('Kalifornisches Stinktier'),
  ('Kalmar'),
  ('Kamel'),
  ('Kamerun-Schaf'),
  ('Kammhuhn'),
  ('Kammkiwi'),
  ('Kammolch'),
  ('Kanadagans'),
  ('Kanadareiher'),
  ('Kangal'),
  ('Kaninchen'),
  ('Kapaffe'),
  ('Kapgeier'),
  ('Kapuzineraffe'),
  ('Kapuzinerspecht'),
  ('Kapuzineräffchen'),
  ('Karaganda-Wolf'),
  ('Karakal'),
  ('Karausche'),
  ('Karettschildkröte'),
  ('Karibikflamingo'),
  ('Karibu'),
  ('Karpfen'),
  ('Karpfenbarsch'),
  ('Karpfenhecht'),
  ('Kartäuser'),
  ('Kashmir-Hirsch'),
  ('Kasuar'),
  ('Katarrhinen'),
  ('Katsuwonus'),
  ('Katta'),
  ('Katze'),
  ('Katzenbär'),
  ('Katzenhai'),
  ('Kauz'),
  ('Kaventsmann'),
  ('Keeler'),
  ('Keeshond'),
  ('Kegelrobbe'),
  ('Kegelschnecke'),
  ('Kellerassel'),
  ('Kennzeichenfrosch'),
  ('Kentucky-Warbler'),
  ('Kettennatter'),
  ('Khabarovsk-Wolf'),
  ('Khao Manee'),
  ('Kiebitz'),
  ('Kiemenechse'),
  ('Killerameise'),
  ('Killerwal'),
  ('King Charles Spaniel'),
  ('Kirschblütenkrabbe'),
  ('Kiwi'),
  ('Klammeraffe'),
  ('Klapper-Klapperschlange'),
  ('Klapperschlange'),
  ('Kleiber'),
  ('Kleidervogel'),
  ('Kleiner Münsterländer'),
  ('Kleinspecht'),
  ('Klettermaus'),
  ('Kliesche'),
  ('Klippenspringer'),
  ('Klippschliefer'),
  ('Knoblauchkröte'),
  ('Knochenfisch'),
  ('Knurrhahn'),
  ('Koala'),
  ('Koati'),
  ('Koboldhai'),
  ('Koboldmaki'),
  ('Kobra'),
  ('Kohlmeise'),
  ('Kojote'),
  ('Kolibri'),
  ('Kolkrabe'),
  ('Komodowaran'),
  ('Komondor'),
  ('Kondor'),
  ('Kooikerhondje'),
  ('Korallennatter'),
  ('Korallenotter'),
  ('Korallenschlange'),
  ('Korat'),
  ('Korkflügel'),
  ('Kormoran'),
  ('Kornnatter'),
  ('Kornweihe'),
  ('Krabbe'),
  ('Krabbentaucher'),
  ('Kragenbär'),
  ('Kragenechse'),
  ('Kragenhai'),
  ('Krake'),
  ('Kranich'),
  ('Krebs'),
  ('Kreischeule'),
  ('Kreuzotter'),
  ('Kreuzschnabel'),
  ('Kreuzspinne'),
  ('Krickente'),
  ('Krokodil'),
  ('Krokodilkaiman'),
  ('Krokodilwächter'),
  ('Kromfohrländer'),
  ('Kronenadler'),
  ('Kronenkranich'),
  ('Kronenlemur'),
  ('Krähe'),
  ('Kröte'),
  ('Kuckuck'),
  ('Kuckuckshummel'),
  ('Kugelgürteltier'),
  ('Kugelspinne'),
  ('Kuh'),
  ('Kuhantilope'),
  ('Kuhreiher'),
  ('Kupferkopf'),
  ('Kupfernatter'),
  ('Kurilen-Stummelschwanzkatze'),
  ('Kurzflossen-Pilotwhal'),
  ('Kurzkopfgleitbeutler'),
  ('Kurzschnabeligel'),
  ('Kurzschwanz-Albatros'),
  ('Kuskus'),
  ('Kuvasz'),
  ('Käfer'),
  ('Känguru'),
  ('Känguruhmaus'),
  ('Kängururatte'),
  ('Käscherfänger'),
  ('Königsadler'),
  ('Königsalbatros'),
  ('Königsfasan'),
  ('Königsglattnatter'),
  ('Königskobra'),
  ('Königskrabbe'),
  ('Königslibelle'),
  ('Königsmakrele'),
  ('Königspython'),
  ('Königstiger'),
  ('Königstöter'),
  ('LaPerm'),
  ('Labradoodle'),
  ('Labrador Retriever'),
  ('Lachfrosch'),
  ('Lachmöwe'),
  ('Lachs'),
  ('Lachseeschwalbe'),
  ('Lachtaube'),
  ('Lagotto Romagnolo'),
  ('Lakeland Terrier'),
  ('Lama'),
  ('Lammergeier'),
  ('Landschildkröte'),
  ('Landseer'),
  ('Languste'),
  ('Lanzennatter'),
  ('Lanzettfischchen'),
  ('Larvensifaka'),
  ('Laubfrosch'),
  ('Laubheuschrecke'),
  ('Laubsänger'),
  ('Laufkäfer'),
  ('Leberblümchenfalter'),
  ('Lederschildkröte'),
  ('Lederwanze'),
  ('Leguan'),
  ('Leierschwanz'),
  ('Leistenkrokodil'),
  ('Lemming'),
  ('Lemur'),
  ('Lemurkatze'),
  ('Leonberger'),
  ('Leopard'),
  ('Leoparden-Hai'),
  ('Leopardgecko'),
  ('Leopardkatze'),
  ('Lepidopteren'),
  ('Lerche'),
  ('Lesser Panda'),
  ('Leuchtkäfer'),
  ('Lhasa Apso'),
  ('Libelle'),
  ('Libellenlarve'),
  ('Liganga-Wolf'),
  ('Limulus'),
  ('Lippfisch'),
  ('Litoria'),
  ('Lockenfalter'),
  ('Lohwels'),
  ('Lori'),
  ('Luchs'),
  ('Lufa'),
  ('Luftaal'),
  ('Lummensturmvogel'),
  ('Lurch'),
  ('Lurchspinne'),
  ('Lykoi'),
  ('Löffelente'),
  ('Löffelpelikan'),
  ('Löffler'),
  ('Löwe'),
  ('Löwenkopfkaninchen'),
  ('Löwenäffchen'),
  ('Maara'),
  ('Madagaskar-Boa'),
  ('Madagaskar-Tag-Gecko'),
  ('Magot'),
  ('Maikäfer'),
  ('Mainau-Maus'),
  ('Maine Coon'),
  ('Makak'),
  ('Makrele'),
  ('Makrelenhecht'),
  ('Malachiteisvogel'),
  ('Malinois'),
  ('Mallard'),
  ('Malteser'),
  ('Mammut'),
  ('Manchester Terrier'),
  ('Mandarinente'),
  ('Mandelkrähe'),
  ('Mandrill'),
  ('Mangabey'),
  ('Mangrovereiher'),
  ('Manta'),
  ('Mantarochen'),
  ('Mantel-Schwein'),
  ('Mantelmöwe'),
  ('Mantispiden'),
  ('Manx'),
  ('Mara'),
  ('Marabu'),
  ('Marder'),
  ('Marderhund'),
  ('Maremmen-Abruzzen-Schäferhund'),
  ('Marienkäfer'),
  ('Marmorente'),
  ('Marmorkarpfen'),
  ('Marmorkrebs'),
  ('Marmorratte'),
  ('Marmorsalamander'),
  ('Marsupilami'),
  ('Massasauga'),
  ('Mastiff'),
  ('Mauerassel'),
  ('Mauerbiene'),
  ('Mauereidechse'),
  ('Mauerfuchs'),
  ('Mauerläufer'),
  ('Mauersegler'),
  ('Maulbrüter'),
  ('Maulesel'),
  ('Maultier'),
  ('Maulwurf'),
  ('Maulwurfsgrille'),
  ('Maus'),
  ('Mausopossum'),
  ('Meerbarbe'),
  ('Meerbarsch'),
  ('Meerechse'),
  ('Meeresgrundel'),
  ('Meeresnacktschnecke'),
  ('Meerforelle'),
  ('Meerkatze'),
  ('Meerkatzenadler'),
  ('Meerneunauge'),
  ('Meerschildkröte'),
  ('Meerschweinchen'),
  ('Meeräsche'),
  ('Mehlkäfer'),
  ('Mehlmotte'),
  ('Mehlschwalbe'),
  ('Meise'),
  ('Mendesantilope'),
  ('Merlin'),
  ('Mexikanische Schopfwachtel'),
  ('Mexikanischer Wolf'),
  ('Miesmuschel'),
  ('Mikroliebellen'),
  ('Milan'),
  ('Milbe'),
  ('Milchfrosch'),
  ('Milchschlange'),
  ('Minkwal'),
  ('Mistkäfer'),
  ('Mittelamerikanischer Tapir'),
  ('Mittelmeer-Mönchsrobbe'),
  ('Mittelmeermuräne'),
  ('Mittelspitz'),
  ('Mittelsäger'),
  ('Molch'),
  ('Monarchfalter'),
  ('Mongolischer Wolf'),
  ('Moorente'),
  ('Moorfrosch'),
  ('Mops'),
  ('Moschusente'),
  ('Moschushirsch'),
  ('Moschusochse'),
  ('Moschusratte'),
  ('Moschusschildkröte'),
  ('Mufflon'),
  ('Munchkin'),
  ('Mungo'),
  ('Mungo-Lemur'),
  ('Murmel'),
  ('Murmeltier'),
  ('Muschel'),
  ('Muschelkrebs'),
  ('Mähnenspringer'),
  ('Mähnenwolf'),
  ('Mönchsgeier'),
  ('Mönchsgrasmücke'),
  ('Mönchsrobbe'),
  ('Möwe'),
  ('Möwentaube'),
  ('Mücke'),
  ('Nachtaffe'),
  ('Nachtfalke'),
  ('Nachtigall'),
  ('Nacktmull'),
  ('Nacktnasenwombat'),
  ('Nacktschnecke'),
  ('Nadeleidechse'),
  ('Nagelfleck'),
  ('Namaqua-Wüstenmaus'),
  ('Nandu'),
  ('Napfschnecke'),
  ('Narrenkleid'),
  ('Narwal'),
  ('Nasenaffe'),
  ('Nasenbeutler'),
  ('Nasenbär'),
  ('Nasenfledermaus'),
  ('Nashorn'),
  ('Nashornkäfer'),
  ('Nashornleguan'),
  ('Natter'),
  ('Natterjack'),
  ('Nautilus'),
  ('Nebelkrähe'),
  ('Nebelparder'),
  ('Nebelungkatze'),
  ('Negerblattläuse'),
  ('Nektarsittich'),
  ('Nektarvogel'),
  ('Nelkenkröte'),
  ('Nemo-Fisch'),
  ('Neonsalmler'),
  ('Nerz'),
  ('Netzpython'),
  ('Neufundlandhund'),
  ('Neufundländer'),
  ('Neuntöter'),
  ('Neuseelandseelöwe'),
  ('Neuweltaffe'),
  ('Nilflughund'),
  ('Nilgans'),
  ('Nilkrokodil'),
  ('Nilpferd'),
  ('Nilwaran'),
  ('Nimmersatt'),
  ('Nonnengans'),
  ('Norddeutscher Spitz'),
  ('Nordseegarneele'),
  ('Nordseekrabbe'),
  ('Norfolk Terrier'),
  ('Norwich Terrier'),
  ('Nova Scotia Duck Tolling Retriever'),
  ('Numbat'),
  ('Nutria'),
  ('Nyala'),
  ('Nördlicher Kaiman'),
  ('Nördlicher See-Elefant'),
  ('Oarfish'),
  ('Ochse'),
  ('Ocicat'),
  ('Ohrenqualle'),
  ('Ohrfleck-Röhrenaal'),
  ('Ohrwurm'),
  ('Okapi'),
  ('Oktopus'),
  ('Old English Sheepdog'),
  ('Olivenpython'),
  ('Olivenschildkröte'),
  ('Olm'),
  ('Onager'),
  ('Opalfink'),
  ('Opisthocomus'),
  ('Opossum'),
  ('Orang-Utan'),
  ('Orca'),
  ('Orca-Wal'),
  ('Orientalische Kurzhaarkatze'),
  ('Orientalische Langhaarkatze'),
  ('Orinoko-Krokodil'),
  ('Ornithorhynchus'),
  ('Orpington-Huhn'),
  ('Ortolan'),
  ('Oryx'),
  ('Osterhase'),
  ('Ostpolnischer Kuhhund'),
  ('Otter'),
  ('Ozelot'),
  ('Pacu'),
  ('Padda'),
  ('Palette-Doktorfisch'),
  ('Palmendieb'),
  ('Palmenflughund'),
  ('Pampashase'),
  ('Pampaskatze'),
  ('Pampasrind'),
  ('Panamakröte'),
  ('Panda'),
  ('Panther'),
  ('Pantheraschnecke'),
  ('Pantherkatze'),
  ('Pantherschildkröte'),
  ('Panzernashorn'),
  ('Papagei'),
  ('Papageifisch'),
  ('Papageitaucher'),
  ('Papillon'),
  ('Paradiesfliegenschnäpper'),
  ('Paradieskranich'),
  ('Paradiesvogel'),
  ('Pardelluchs'),
  ('Parkmotte'),
  ('Parnassius'),
  ('Parson Russell Terrier'),
  ('Pavian'),
  ('Pazifischer Riesenkrake'),
  ('Peccari'),
  ('Pegusus'),
  ('Pekari'),
  ('Pekinese'),
  ('Pelikan'),
  ('Pelikanaal'),
  ('Pendelaffe'),
  ('Penntungara'),
  ('Perlboot'),
  ('Perleidechse'),
  ('Perlhalstaube'),
  ('Perlhuhn'),
  ('Perlmuschel'),
  ('Perlmutterfalter'),
  ('Perro de Agua Español'),
  ('Persische Katze'),
  ('Persischer Leopard'),
  ('Peterbald'),
  ('Petrochelidon'),
  ('Pfau'),
  ('Pfauenauge'),
  ('Pfauentaube'),
  ('Pfeifhase'),
  ('Pfeilgiftfrosch'),
  ('Pfeilschwanz'),
  ('Pfeilschwanzkrebs'),
  ('Pferd'),
  ('Pferdeantilope'),
  ('Pferdebremse'),
  ('Pferdeegel'),
  ('Pfuhlschnepfe'),
  ('Pharaonenhund'),
  ('Phragmiten'),
  ('Pieper'),
  ('Pillendrehr'),
  ('Pinakate'),
  ('Pinguin'),
  ('Pinscher'),
  ('Pinselohrschwein'),
  ('Pinto'),
  ('Piranha'),
  ('Pirol'),
  ('Pixiebob'),
  ('Plattentenrek'),
  ('Plattenwurm'),
  ('Plattfisch'),
  ('Plattfußechse'),
  ('Plattnas'),
  ('Podenco Ibicenco'),
  ('Pointer'),
  ('Polarbär'),
  ('Polarfuchs'),
  ('Polarvogel'),
  ('Polarwolf'),
  ('Pomeranian'),
  ('Pony'),
  ('Posthornschnecke'),
  ('Pottwal'),
  ('Prachtfink'),
  ('Prachtfregattvogel'),
  ('Prachthibiskus'),
  ('Prachtkleinlibelle'),
  ('Prachtlibelle'),
  ('Prachttaucher'),
  ('Przewalski-Pferd'),
  ('Präriehund'),
  ('Pudel'),
  ('Puli'),
  ('Puma'),
  ('Pumi'),
  ('Punktbarbe'),
  ('Purpurgallinule'),
  ('Purpurreiher'),
  ('Pustelschwein'),
  ('Puter'),
  ('Putoranschneeschaf'),
  ('Puzuh'),
  ('Pyrenäenberghund'),
  ('Python'),
  ('Qualle'),
  ('Quappe'),
  ('Quellschnecke'),
  ('Querzahnmolch'),
  ('Quetzal'),
  ('Quokka'),
  ('Rabe'),
  ('Rabenkakadu'),
  ('Rabenkrähe'),
  ('Ragamuffin'),
  ('Ragdoll'),
  ('Raggi-Paradiesvogel'),
  ('Rallenkranich'),
  ('Randspecht'),
  ('Rappenantilope'),
  ('Ratte'),
  ('Raubwürger'),
  ('Rauchquarz-Klapperschlange'),
  ('Rauchschwalbe'),
  ('Raufußbussard'),
  ('Rauhautfledermaus'),
  ('Rauhfußkauz'),
  ('Rauhhaardackel'),
  ('Raupe'),
  ('Rauschwalbe'),
  ('Rebhuhn'),
  ('Regenbogenforelle'),
  ('Regenpfeifer'),
  ('Regenwald-Frosch'),
  ('Regenwurm'),
  ('Regenwurmbussard'),
  ('Reh'),
  ('Reiher'),
  ('Reiherente'),
  ('Reisfink'),
  ('Renke'),
  ('Rennkäfer'),
  ('Rennvogel'),
  ('Rentier'),
  ('Rhesusaffe'),
  ('Rhipidomys'),
  ('Rhodesian Ridgeback'),
  ('Riedmaus'),
  ('Riesenameisenbär'),
  ('Riesenanakonda'),
  ('Riesenfaultier'),
  ('Riesengarnele'),
  ('Riesengürteltier'),
  ('Riesenhai'),
  ('Riesenhirsch'),
  ('Riesenibis'),
  ('Riesenkalmar'),
  ('Riesenkrake'),
  ('Riesenkänguru'),
  ('Riesenmuräne'),
  ('Riesenmuschel'),
  ('Riesenotter'),
  ('Riesenpanda'),
  ('Riesenpinguin'),
  ('Riesenrotbarsch'),
  ('Riesensalamander'),
  ('Riesenschildkröte'),
  ('Riesenschlange'),
  ('Riesenschnauzer'),
  ('Riesenseeadler'),
  ('Riesensturmvogel'),
  ('Riesentintenfisch'),
  ('Riesentukan'),
  ('Riffbarsch'),
  ('Riffbussard'),
  ('Riffhai'),
  ('Rind'),
  ('Ringelblatt'),
  ('Ringelgans'),
  ('Ringelnatter'),
  ('Ringelnatternfresser'),
  ('Ringelpitti'),
  ('Ringeltaube'),
  ('Rippenqualle'),
  ('Robbe'),
  ('Rochen'),
  ('Roetelfalke'),
  ('Rohrdommel'),
  ('Rohrkolbenschmetterling'),
  ('Rohrweihe'),
  ('Rosaflamingo'),
  ('Rosalöffler'),
  ('Roselle'),
  ('Rosenfink'),
  ('Rosenkäfer'),
  ('Rotaugenlaubfrosch'),
  ('Rotbartmaki'),
  ('Rotbauchammer'),
  ('Rotbauchsalamander'),
  ('Rotbauchunke'),
  ('Rotbrustgans'),
  ('Rotdrossel'),
  ('Rote Kratzhonigbiene'),
  ('Rote Mamba'),
  ('Rotemu'),
  ('Roter Panda'),
  ('Roter Vari'),
  ('Rotfederfisch'),
  ('Rotfeuerfisch'),
  ('Rotflügel-Brachschwalbe'),
  ('Rotfuchs'),
  ('Rotgesichtskormoran'),
  ('Rotgesichtsmakak'),
  ('Rothirsch'),
  ('Rotkappenpinguin'),
  ('Rotkardinal'),
  ('Rotkehlchen'),
  ('Rotkehlpieper'),
  ('Rotluchs'),
  ('Rotmaulsalmler'),
  ('Rotmilan'),
  ('Rotnacken-Wallaby'),
  ('Rotrückenspinne'),
  ('Rotschenkel'),
  ('Rotschnabelstar'),
  ('Rotschwanzbussard'),
  ('Rotschwanzmaki'),
  ('Rottweiler'),
  ('Rotwild'),
  ('Rotwolf'),
  ('Ruderente'),
  ('Russ-Falke'),
  ('Russenbär'),
  ('Russisch Blau'),
  ('Rötelmaus'),
  ('Rüsselhündchen'),
  ('Rüsselratte'),
  ('Rüsselrobbe'),
  ('Rüsselspringer'),
  ('Saiblingsforelle'),
  ('Saiga'),
  ('Saigaantilope'),
  ('Sakipalmensittich'),
  ('Salamander'),
  ('Salbei-Auerhuhn'),
  ('Saluki'),
  ('Salzwasserkrokodil'),
  ('Sambar-Hirsch'),
  ('Samojede'),
  ('Sandboa'),
  ('Sandfisch'),
  ('Sandfuchs'),
  ('Sandgazelle'),
  ('Sandkatze'),
  ('Sandlaufkäfer'),
  ('Sandregenpfeifer'),
  ('Sandregenwurm'),
  ('Sandtigerhai'),
  ('Sandviper'),
  ('Sardine'),
  ('Saruskranich'),
  ('Sattelrobbe'),
  ('Sattelschwein'),
  ('Sattelstörch'),
  ('Saumwels'),
  ('Sauthier'),
  ('Savannah'),
  ('Schabe'),
  ('Schabenkrebs'),
  ('Schabrackentapir'),
  ('Schaf'),
  ('Schakal'),
  ('Schalbenschwanz'),
  ('Schamane-Pfeilgiftfrosch'),
  ('Schaufelbart'),
  ('Schaufelnashorn'),
  ('Schaufelschnabel'),
  ('Schaufelstör'),
  ('Scheckkrabbe'),
  ('Schellente'),
  ('Schellfisch'),
  ('Schichtkrabbe'),
  ('Schildbär'),
  ('Schildkröte'),
  ('Schimmel'),
  ('Schimpanse'),
  ('Schipperke'),
  ('Schlange'),
  ('Schlangenadler'),
  ('Schlangenhalsvogel'),
  ('Schlangenstern'),
  ('Schleichkatze'),
  ('Schleie'),
  ('Schleiereule'),
  ('Schleimaal'),
  ('Schleimfisch'),
  ('Schmalfuß-Beutelmaus'),
  ('Schmalkopfratte'),
  ('Schmalmaul-Krokodil'),
  ('Schmarotzer-Möwe'),
  ('Schmerle'),
  ('Schmetterling'),
  ('Schmuckschildkröte'),
  ('Schmutzgeier'),
  ('Schnabeltier'),
  ('Schnappschildkröte'),
  ('Schnatterente'),
  ('Schnecke'),
  ('Schneeaffe'),
  ('Schneealbatros'),
  ('Schneeammer'),
  ('Schneeeule'),
  ('Schneefink'),
  ('Schneeflocken-Muräne'),
  ('Schneehase'),
  ('Schneeleopard'),
  ('Schnurrwurm'),
  ('Schopflerche'),
  ('Schopfpinguin'),
  ('Schopfwachtel'),
  ('Schornsteinsegler'),
  ('Schottischer Terrier'),
  ('Schraubenhornziege'),
  ('Schreiadler'),
  ('Schwalbenschwanz'),
  ('Schwalbensturmvogel'),
  ('Schwan'),
  ('Schwanzlurch'),
  ('Schwarzaffe'),
  ('Schwarzbarsch'),
  ('Schwarzbär'),
  ('Schwarzbüffel'),
  ('Schwarzdorn-Apollofalter'),
  ('Schwarzelster'),
  ('Schwarzfußkatze'),
  ('Schwarzhalsschwan'),
  ('Schwarzhalstaucher'),
  ('Schwarzkappen-Lori'),
  ('Schwarzkehlchen'),
  ('Schwarzkopfgibbon'),
  ('Schwarzkopfmöwe'),
  ('Schwarzlachs'),
  ('Schwarzmilan'),
  ('Schwarznasenhai'),
  ('Schwarzracke'),
  ('Schwarzrückenschakal'),
  ('Schwarzscheitel-Bülbül'),
  ('Schwarzspecht'),
  ('Schwarzstirnwürger'),
  ('Schwarzstorch'),
  ('Schwarzweißer Vari'),
  ('Schwarzwild'),
  ('Schwein'),
  ('Schweinswal'),
  ('Schwertfisch'),
  ('Schwertschnabel'),
  ('Schwertwal'),
  ('Schädelmotte'),
  ('Schäferhund'),
  ('Scottish Fold'),
  ('Sechskiemerhai'),
  ('Seeadler'),
  ('Seeanemone'),
  ('Seebarbe'),
  ('Seedrache'),
  ('Seegurke'),
  ('Seehase'),
  ('Seehund'),
  ('Seekatze'),
  ('Seekreuzotter'),
  ('Seekuh'),
  ('Seeleopard'),
  ('Seelöwe'),
  ('Seenadel'),
  ('Seepferdchen'),
  ('Seerose'),
  ('Seeschwalbe'),
  ('Seestern'),
  ('Seeteufel'),
  ('Seewolf'),
  ('Seezunge'),
  ('Segelfisch'),
  ('Seidenaffe'),
  ('Seidenkuckuck'),
  ('Seidenraupe'),
  ('Seidenreiher'),
  ('Sekretär'),
  ('Selkirk Rex'),
  ('Senftaube'),
  ('Serengeti'),
  ('Serval'),
  ('Sesame'),
  ('Shar Pei'),
  ('Sheltie'),
  ('Shetland-Schaf'),
  ('Shetlandpony'),
  ('Shiba Inu'),
  ('Shih Tzu'),
  ('Siamang'),
  ('Siamkatze'),
  ('Siberian Husky'),
  ('Sibirische Katze'),
  ('Sibirischer Tiger'),
  ('Sichelkönig'),
  ('Sichlerstorch'),
  ('Sidewinder'),
  ('Siebenschläfer'),
  ('Sika-Hirsch'),
  ('Silberfasan'),
  ('Silberfischchen'),
  ('Silberhalbflanken-Saimi'),
  ('Silberlachs'),
  ('Silbermöwe'),
  ('Silberreiher'),
  ('Silberäffchen'),
  ('Sing-Rallen'),
  ('Singapura'),
  ('Singschwann'),
  ('Sittich'),
  ('Skarabäus'),
  ('Skipjack'),
  ('Skorpion'),
  ('Skorpionfisch'),
  ('Skua'),
  ('Skunk'),
  ('Skye Terrier'),
  ('Sloughi'),
  ('Smaragdeidechse'),
  ('Smaragdwaran'),
  ('Snowshoe'),
  ('Sokoke'),
  ('Somali'),
  ('Sommerfalter'),
  ('Sonnenbarsch'),
  ('Sonnenralle'),
  ('Sonnentierchen'),
  ('Sori-Lemur'),
  ('Spaltmaus'),
  ('Spanische Wegschnecke'),
  ('Specht'),
  ('Sperber'),
  ('Sperbereule'),
  ('Sperbergeier'),
  ('Sphingidae'),
  ('Sphinxmotte'),
  ('Sphynx'),
  ('Spiegelfink'),
  ('Spiegelkarpfen'),
  ('Spinne'),
  ('Spinnenkrabbe'),
  ('Spinone Italiano'),
  ('Spitzhörnchen'),
  ('Spitzkrokodil'),
  ('Spitzmaus'),
  ('Spitzschwanzkrabbe'),
  ('Spornkuckuck'),
  ('Spottdrossel'),
  ('Springbock'),
  ('Springer'),
  ('Springfrosch'),
  ('Springmaus'),
  ('Springpfeifgras'),
  ('Springratte'),
  ('Stabheuschrecke'),
  ('Stabschrecke'),
  ('Stachelaal'),
  ('Stachelameisenbär'),
  ('Stachelmaus'),
  ('Stachelrochen'),
  ('Stachelschwein'),
  ('Staffordshire Bullterrier'),
  ('Stahlblauer Grillenjäger'),
  ('Stahlfink'),
  ('Stahlschildkröte'),
  ('Star'),
  ('Stechfliege'),
  ('Stechmücke'),
  ('Stechrochen'),
  ('Steinadler'),
  ('Steinbeißer'),
  ('Steinbock'),
  ('Steinbutt'),
  ('Steindrossel'),
  ('Steinkauz'),
  ('Steinklatscher'),
  ('Steinkrabbe'),
  ('Steinläufer'),
  ('Steinmarder'),
  ('Steinrötel'),
  ('Steinwälzer'),
  ('Stentor'),
  ('Steppenadler'),
  ('Steppenfuchs'),
  ('Steppeniltis'),
  ('Steppenlemming'),
  ('Steppenmanguste'),
  ('Steppensaiga'),
  ('Steppenwaran'),
  ('Steppenzebra'),
  ('Sternchen-Wels'),
  ('Sternenschwarm'),
  ('Sternhausen'),
  ('Sternkoralle'),
  ('Stichling'),
  ('Stiefelkatze'),
  ('Stieglitz'),
  ('Stierkopfhai'),
  ('Stinkdachs'),
  ('Stinkkäfer'),
  ('Stinktier'),
  ('Stockente'),
  ('Stockschwertträger'),
  ('Storch'),
  ('Strandkrabbe'),
  ('Strandregenpfeifer'),
  ('Strauß'),
  ('Streifenadler'),
  ('Streifengnu'),
  ('Streifenhyäne'),
  ('Streifenhörnchen'),
  ('Streifenkiwi'),
  ('Streifenmungo'),
  ('Streifenotter'),
  ('Streifenschnabelente'),
  ('Streifenwels'),
  ('Stubenfliege'),
  ('Stummelaffe'),
  ('Stummelschwanzchamäleon'),
  ('Sturmschwalbe'),
  ('Sturmtaucher'),
  ('Stör'),
  ('Suaheli-Wachtel'),
  ('Sumpfbiber'),
  ('Sumpfhuhn'),
  ('Sumpfkrokodil'),
  ('Sumpfmeise'),
  ('Sumpfohreule'),
  ('Sumpfrohrsänger'),
  ('Sumpfschildkröte'),
  ('Säbelschnäbler'),
  ('Säbelzahntiger'),
  ('Sägebock'),
  ('Sägefisch'),
  ('Säugetier'),
  ('Südlicher Glattwal'),
  ('Südlicher Seeelefant'),
  ('Süßwasserkrabbe'),
  ('Tafelente'),
  ('Taggecko'),
  ('Taglilien-Schmetterling'),
  ('Tagpfauenauge'),
  ('Taipan'),
  ('Tamandua'),
  ('Tamarin'),
  ('Tannenhäher'),
  ('Tannenmeise'),
  ('Tannentriel'),
  ('Tannenzeisig'),
  ('Tantal'),
  ('Tapir'),
  ('Tarantel'),
  ('Tarantelfalke'),
  ('Tasmanischer Beutelmarder'),
  ('Tasmanischer Riesenkrebs'),
  ('Tasmanischer Teufel'),
  ('Tasmanischer Wolf'),
  ('Taube'),
  ('Taucherente'),
  ('Tausendfüßer'),
  ('Teichfrosch'),
  ('Teichhuhn'),
  ('Teichlibelle'),
  ('Teichmolch'),
  ('Teichmuschel'),
  ('Teichralle'),
  ('Teichrohrsänger'),
  ('Teichwasserläufer'),
  ('Tellerschnecke'),
  ('Tengmalmeise'),
  ('Tenrek'),
  ('Termite'),
  ('Tervueren'),
  ('Texashörnchen'),
  ('Thai-Katze'),
  ('Thaukuh'),
  ('Thresher'),
  ('Thunfisch'),
  ('Tibet Terrier'),
  ('Tibetan Mastiff'),
  ('Tibetantilope'),
  ('Tibetfuchs'),
  ('Tibetzwergmaus'),
  ('Tiffanie'),
  ('Tiger'),
  ('Tigerameise'),
  ('Tigergecko'),
  ('Tigerhai'),
  ('Tigerkatze'),
  ('Tigermücke'),
  ('Tigerpython'),
  ('Tigersalamander'),
  ('Tigerschnegel'),
  ('Timberwolf'),
  ('Tinamu'),
  ('Tintenfisch'),
  ('Tonkinese'),
  ('Topfschnecke'),
  ('Topi'),
  ('Torpedorochen'),
  ('Totenkopfaffe'),
  ('Toyger'),
  ('Toypudel'),
  ('Trampeltier'),
  ('Trauermantel'),
  ('Trauerschwan'),
  ('Trauerseeschwalbe'),
  ('Triel'),
  ('Tropenpinguin'),
  ('Tropfenfisch'),
  ('Tropikvogel'),
  ('Trugratte'),
  ('Truthahn'),
  ('Truthahngeier'),
  ('Tsavolöwe'),
  ('Tschechoslowakischer Wolfhund'),
  ('Tsetsefliege'),
  ('Tukan'),
  ('Turmfalke'),
  ('Töpferwespe'),
  ('Tümmler'),
  ('Tüpfelhyäne'),
  ('Tüpfelsumpfhuhn'),
  ('Türkenente'),
  ('Türkentaube'),
  ('Türkisch Angora'),
  ('Türkisch Van'),
  ('Türkisturako'),
  ('Uakari'),
  ('Uferschnepfe'),
  ('Uguisu'),
  ('Uhu'),
  ('Ukelei'),
  ('Ukrainische Levkoy'),
  ('Umbrettstorch'),
  ('Ungarischer Vizsla'),
  ('Unke'),
  ('Ur'),
  ('Ural-Eule'),
  ('Urbansumpfschildkröte'),
  ('Urdur'),
  ('Urial'),
  ('Ursachsenmolch'),
  ('Ursaurier'),
  ('Urwaldkönig'),
  ('Ussurischer Tiger'),
  ('Vampirfledermaus'),
  ('Vampirtintenfisch'),
  ('Vaquita'),
  ('Variegated Squirrel'),
  ('Venezuela-Buschgrille'),
  ('Vielfraß'),
  ('Viktoriakronentaube'),
  ('Vikunja'),
  ('Viper'),
  ('Virginia-Uhu'),
  ('Vogelspinne'),
  ('Vorderasiatischer Leopard'),
  ('Wachhund'),
  ('Wachtel'),
  ('Wachtelkönig'),
  ('Wal'),
  ('Waldeidechse'),
  ('Waldkauz'),
  ('Waldlaubsänger'),
  ('Waldmaus'),
  ('Waldohreule'),
  ('Waldschabe'),
  ('Waldschnepfe'),
  ('Walhai'),
  ('Wallaby'),
  ('Walross'),
  ('Wandelndes Blatt'),
  ('Wanderfalke'),
  ('Wanderheuschrecke'),
  ('Wanderkrabbe'),
  ('Wandermuschel'),
  ('Wanderratte'),
  ('Wapitihirsch'),
  ('Warzenschwein'),
  ('Waschbär'),
  ('Waschbärhund'),
  ('Wasseramsel'),
  ('Wasserbock'),
  ('Wasserbüffel'),
  ('Wasserdrache'),
  ('Wasserfledermaus'),
  ('Wasserfloh'),
  ('Wasserfrosch'),
  ('Wasserlibelle'),
  ('Wasserläufer'),
  ('Wassermanguste'),
  ('Wassermolch'),
  ('Wasserotter'),
  ('Wasserpython'),
  ('Wasserralle'),
  ('Wasserschildkröte'),
  ('Wasserschlange'),
  ('Wasserschwein'),
  ('Wasserspitzmaus'),
  ('Wasserwaran'),
  ('Webervogel'),
  ('Webspinne'),
  ('Wechselkröte'),
  ('Weddellrobbe'),
  ('Wegerich-Scheckenfalter'),
  ('Wegwespe'),
  ('Weichkäfer'),
  ('Weichschildkröte'),
  ('Weidenmeise'),
  ('Weihe'),
  ('Weimaraner'),
  ('Weinbergschnecke'),
  ('Weinschwärmer'),
  ('Weißbart-Saki'),
  ('Weißbauchaffe'),
  ('Weißbauchigel'),
  ('Weißbauchseeadler'),
  ('Weißbüschelaffe'),
  ('Weißer Hai'),
  ('Weißfingerkrebs'),
  ('Weißflanken-Delfin'),
  ('Weißhandgibbon'),
  ('Weißkehlsänger'),
  ('Weißkopfgeier'),
  ('Weißkopfseeadler'),
  ('Weißlippenpekari'),
  ('Weißmaulhirsch'),
  ('Weißrandfledermaus'),
  ('Weißritterhonigfresser'),
  ('Weißrückengeier'),
  ('Weißscheitelrötel'),
  ('Weißschnabeltaucher'),
  ('Weißstirnamazone'),
  ('Weißstorch'),
  ('Weißwedelhirsch'),
  ('Wellensittich'),
  ('Wels'),
  ('Welsh Corgi'),
  ('Welsh Terrier'),
  ('Wendehals'),
  ('Wespe'),
  ('Wespenbussard'),
  ('West Highland White Terrier'),
  ('Westafrikanischer Leopard'),
  ('Westkaplöwe'),
  ('Westkaukasischer Steinbock'),
  ('Whippet'),
  ('Wickelbär'),
  ('Widder'),
  ('Wiedehopf'),
  ('Wiesel'),
  ('Wieselmaki'),
  ('Wiesenotter'),
  ('Wiesenpieper'),
  ('Wiesenralle'),
  ('Wiesenweihe'),
  ('Wildgans'),
  ('Wildkatze'),
  ('Wildpferd'),
  ('Wildschaf'),
  ('Wildschwein'),
  ('Wildtaube'),
  ('Winkelspinne'),
  ('Winkerkrabbe'),
  ('Wintergoldhähnchen'),
  ('Wisent'),
  ('Wolf'),
  ('Wolfsbarsch'),
  ('Wolfsfisch'),
  ('Wolfshund'),
  ('Wolfsspitz'),
  ('Wollaffe'),
  ('Wollhandkrabbe'),
  ('Wollschwein'),
  ('Wombat'),
  ('Wurm'),
  ('Wühlmaus'),
  ('Wüstenechse'),
  ('Wüstenfuchs'),
  ('Wüstenhamster'),
  ('Wüstenigel'),
  ('Wüstenluchs'),
  ('Wüstenmaus'),
  ('Wüstennatter'),
  ('Wüstenrennmaus'),
  ('Wüstenspringmaus'),
  ('Wüstenwaran'),
  ('Xantusiidae'),
  ('Xenartho'),
  ('Xenopus'),
  ('Xenosaurus'),
  ('Xerus'),
  ('Xoloitzcuintle'),
  ('Yak'),
  ('Yapok'),
  ('Yellowstone-Wolf'),
  ('Yokohamahuhn'),
  ('York Chocolate'),
  ('Yorkshire Terrier'),
  ('Zackenbarsch'),
  ('Zackennatter'),
  ('Zackenschnecke'),
  ('Zander'),
  ('Zaunammer'),
  ('Zauneidechse'),
  ('Zaunkönig'),
  ('Zebra'),
  ('Zebrafink'),
  ('Zebrahai'),
  ('Zebramanguste'),
  ('Zebramuräne'),
  ('Zebraspinne'),
  ('Zecke'),
  ('Zedernseidenschwanz'),
  ('Zentralasiatischer Wolf'),
  ('Zerge'),
  ('Zibetkatze'),
  ('Ziege'),
  ('Ziegenmelker'),
  ('Ziesel'),
  ('Zikade'),
  ('Zilpzalp'),
  ('Zimtbär'),
  ('Zitronenfalter'),
  ('Zitronenhai'),
  ('Zitronenstelzenläufer'),
  ('Zitteraal'),
  ('Zitterrochen'),
  ('Zobel'),
  ('Zorilla'),
  ('Zuchtlachs'),
  ('Zwergadler'),
  ('Zwergaffe'),
  ('Zwergameise'),
  ('Zwergameisenbär'),
  ('Zwergantilope'),
  ('Zwergchirp'),
  ('Zwergdommel'),
  ('Zwergelefant'),
  ('Zwergente'),
  ('Zwergfledermaus'),
  ('Zwergflusspferd'),
  ('Zwerggnu'),
  ('Zwerggürteltier'),
  ('Zwerghamster'),
  ('Zwergkaiman'),
  ('Zwergkaninchen'),
  ('Zwergkatze'),
  ('Zwergkrokodil'),
  ('Zwergmanguste'),
  ('Zwergmaus'),
  ('Zwergmurmel'),
  ('Zwergnashorn'),
  ('Zwergohreule'),
  ('Zwergotter'),
  ('Zwergpapagei'),
  ('Zwergpinguin'),
  ('Zwergpinscher'),
  ('Zwergpudel'),
  ('Zwergpython'),
  ('Zwergschnauzer'),
  ('Zwergschnepfe'),
  ('Zwergspinne'),
  ('Zwergspitz'),
  ('Zwergspitzmaus'),
  ('Zwergstachelschwein'),
  ('Zwergsteinbock'),
  ('Zwergsäger'),
  ('Zwergtaucher'),
  ('Zwergtukan'),
  ('Zwergwal'),
  ('Zwergwels'),
  ('Zwergziege')
),
prepared as (
  select
    trim(name) as name,
    public.normalize_animal_name(name) as norm,
    regexp_replace(public.normalize_animal_name(name), '[^a-z]', '', 'g') as letters_only
  from new_animals
)
insert into public.animals (name, normalized_name, first_letter, last_letter, language, status)
select distinct on (norm)
  name,
  norm,
  substr(letters_only, 1, 1) as first_letter,
  substr(letters_only, length(letters_only), 1) as last_letter,
  'de',
  'approved'
from prepared
where name <> ''
  and norm <> ''
  and length(letters_only) >= 1
order by norm, name
on conflict (normalized_name) do nothing;
